name: clone-tabnews

services:
  web:
    build:
      context: ..
      dockerfile: infra/Dockerfile.prod

    restart: unless-stopped

    env_file:
      - .env

#    depends_on:
#      database:
#        condition: service_healthy

    networks:
      - proxy
#      - internal

    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy

      - traefik.http.routers.clone-tabnews.rule=Host(`${APP_DOMAIN}`)
      - traefik.http.routers.clone-tabnews.entrypoints=websecure
      - traefik.http.routers.clone-tabnews.tls=true
      - traefik.http.routers.clone-tabnews.tls.certresolver=letsencrypt

      - traefik.http.services.clone-tabnews.loadbalancer.server.port=3000

#  database:
#    image: postgres:16-alpine
#
#    restart: unless-stopped
#
#    environment:
#      POSTGRES_DB: ${POSTGRES_DB}
#      POSTGRES_USER: ${POSTGRES_USER}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#
#    networks:
#      - internal
#
#    healthcheck:
#      test:
#        [
#          "CMD-SHELL",
#          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
#        ]
#      interval: 10s
#      timeout: 5s
#      retries: 5
#      start_period: 10s

#volumes:
#  postgres_data:

networks:
  proxy:
    external: true

#  internal:
#    driver: bridge
